name = "CubicBSplineInterpolation"
uuid = "cea239a1-aef7-4735-a0ad-35c493ad27cc"
authors = ["Roy Chih Chung Wang <roy.c.c.wang@proton.me>"]
version = "0.4.10"

[deps]

[compat]
FiniteDiff = "2.26.0"
julia = "1.11"
Random = "1.11.0"

[extras]
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FiniteDiff", "LinearAlgebra", "Random", "Test"]
